mvn spring-boot:runspring.application.name=mailsystem
spring.data.mongodb.database=college_mail_system
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yash.chandnani07@gmail.com
spring.mail.password=ubuv vlrc lgqt boee
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
